#scripts/descriptive_tables/acoustic_tbl_dissertation.R


# Table: acoustic_tbl_dissertation
# Description: This table provides a sample of acoustic measurements for specific phonetic tokens in the study.
#              The table includes the host word, phonetic token, token duration (DURMS), surface form, and four
#              F1 formant steps. The data is selected to represent various phoneme and surface forms, with IPA 
#              symbols formatted for LaTeX.
# Usage: The table is created by filtering the cleaned dataset to include specific phoneme and surface forms, 
#        excluding any rows with missing data. The filtered data is then sampled to provide a representative 
#        subset of the tokens. The LaTeX table generated by this script closely mirrors the desired format 
#        for inclusion in the dissertation, with minimal manual adjustment needed.
# Note: This table uses a random sample so it will not generate the exact same values every single time



# # Load necessary libraries
# library(dplyr)
# library(kableExtra)
# library(readr)
# library(stringr)
# 
# # Load cleaned data from liquids_cleaned.rds
# liquids <- readRDS("data/cleaned_data/liquids_cleaned.rds")


# "[∅]", "[ð]", "[h]", "[i]", "[l]", "[ɫ]", "[r]", "[r̝]", "[ɹ]", "[ɽ]", "[ɾ]", "[v]", "[x]", "[ʔ]"

## Filter and prepare the data
# Specify the phoneme forms and surface form to include

# Specify the phoneme forms and surface forms you want to include
phoneme_forms <- c("/l/", "/r/", "/ɾ/")
surf_forms <- c("[∅]", "[h]", "[l]", "[ɫ]", "[r]", "[ɹ]", "[ɽ]", "[ɾ]", "[x]", "[ʔ]")


filtered_data <- liquids %>%
  filter(PHONO_FORM %in% phoneme_forms & SURF_FORM %in% surf_forms) %>%
  filter(!is.na(PHONO_FORM) & !is.na(SURF_FORM) & !is.na(PHONO_FORM_DURMS)) %>%
  filter_at(vars(F1_STEP1:F1_STEP4), all_vars(!is.na(.)))


# Add an ID column for reference
acoustic_tbl <- filtered_data %>%
  mutate(id = row_number()) %>%
  # Select relevant columns
  select(HOSTWORD, PHONO_FORM, PHONO_FORM_DURMS, SURF_FORM, F1_STEP1:F1_STEP4) %>%
  # Randomly sample a specified number of rows
  sample_n(size = 10)

# Replace IPA symbols with LaTeX commands in PHONO_FORM and SURF_FORM
acoustic_tbl <- acoustic_tbl%>%
  mutate(
    PHONO_FORM = recode(PHONO_FORM,
                        "/ɾ/" = "/\\textfishhookr/",
                        "/r/" = "/r/",
                        "/l/" = "/l/"),  # Replace other IPA symbols as needed
    SURF_FORM = recode(SURF_FORM,
                       "[ɾ]" = "[\\textfishhookr]",
                       "[r]" = "[r]",
                       "[ɹ]" = "[\\textturnr]",
                       "[ɽ]" = "[\\textfishhookrturn]",
                       "[∅]" = "[\\textnull]",
                       "[l]" = "[l]",
                       "[ɫ]" = "[\\textbeltl]",
                       "[ʔ]" = "[\\textglotstop]",
                       "[h]" = "[h]",
                       "[x]" = "[x]",
                       "[ð]" = "[\\dh]",
                       "[i]" = "[i]",
                       "[v]" = "[v]")  # Replace other IPA symbols as needed
  )


# Display the filtered and sampled data
print(acoustic_tbl)


# Create and save the LaTeX table
acoustic_tbl %>%
  kbl("latex", booktabs = TRUE, digits = 2, escape = FALSE, 
      align = c("l", "c", "c", "c", "c", "c", "c", "c"), 
      # caption = "Example of Acoustic Descriptions", label = "acoustic", 
      col.names = c(
        "\\shortstack{\\textsc{Host} \\\\ \\textsc{Word}}",
        "\\shortstack{\\textsc{Phono} \\\\ \\textsc{Token}}",
        "\\shortstack{\\textsc{Token} \\\\ \\textsc{DURMS}}",
        "\\shortstack{\\textsc{Surface} \\\\ \\textsc{Form}}",
        "\\shortstack{\\textsc{F1:} \\\\ \\textsc{Step1}}",
        "\\shortstack{\\textsc{F1:} \\\\ \\textsc{Step2}}",
        "\\shortstack{\\textsc{F1:} \\\\ \\textsc{Step3}}",
        "\\shortstack{\\textsc{F1:} \\\\ \\textsc{Step4}}"
      )) %>%
  kable_styling(latex_options = c("striped"), font_size = 8) %>%
  column_spec(1, width = "4em") %>%
  column_spec(2:8, width = "5em") %>%
  # footnote( fixed_small_size = T, symbol = c("Source: SIB Speaker 0049PR"),
            # threeparttable=T) %>% 
  footnote(fixed_small_size = T, general = c("\\emph{Source:} {Spanish in Boston Corpus \n Vidal Covas' Dissertation Speakers}"),
      threeparttable=T) %>% 
  save_kable(file = "output/tables/descriptive/acoustic_tbl_dissertation.tex")
